name: Continuous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.1
      - name: Install dependencies
        run: poetry install
      - name: Run flake8
        run: poetry run flake8
      - uses: psf/black@stable
